version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-net

  odoo:
    image: odoo:16
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./custom-addons:/mnt/extra-addons
    networks:
      - odoo-net

networks:
  odoo-net:

volumes:
  odoo-db-data:
