name: Deploy Odoo with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev python3-venv python3-pip libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev build-essential libssl-dev libmysqlclient-dev postgresql

      - name: Start PostgreSQL service
        run: |
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo systemctl status postgresql

      - name: Install PostgreSQL and configure user
        run: |
          sudo -u postgres psql -c "CREATE USER odoo WITH PASSWORD 'odoo';"
          sudo -u postgres psql -c "CREATE DATABASE odoo OWNER odoo;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE odoo TO odoo;"

      - name: Create Odoo virtual environment
        run: |
          cd /opt
          git clone --depth=1 --branch 16.0 https://github.com/odoo/odoo.git ./odoo
          sudo chown $USER:$USER odoo
          cd odoo
          python3 -m venv odoo-venv
          source odoo-venv/bin/activate
          pip install -r /opt/odoo/requirements.txt

      - name: Configure Odoo
        run: |
          sudo cp /opt/odoo/debian/odoo.conf /etc/odoo.conf
          sudo sed -i 's/^admin_passwd = .*/admin_passwd = admin/' /etc/odoo.conf
          sudo sed -i 's/^db_host = .*/db_host = False/' /etc/odoo.conf
          sudo sed -i 's/^db_port = .*/db_port = False/' /etc/odoo.conf
          sudo sed -i 's/^db_user = .*/db_user = odoo/' /etc/odoo.conf
          sudo sed -i 's/^db_password = .*/db_password = False/' /etc/odoo.conf
          sudo sed -i 's/^db_name = .*/db_name = odoo/' /etc/odoo.conf

      - name: Create necessary directories for Odoo logs
        run: |
          sudo mkdir /var/log/odoo
          sudo chown $USER:$USER /var/log/odoo

      - name: Start Odoo
        run: |
          cd /opt/odoo
          ./odoo-bin -c /etc/odoo.conf &
        
      - name: Wait for Odoo to start
        run: |
          until curl -s http://localhost:8069; do
            echo "Waiting for Odoo to start..."
            sleep 5
          done

      - name: Display Odoo URL
        run: |
          echo "Odoo is running at http://localhost:8069"

      - name: Test Odoo Deployment
        run: |
          curl http://localhost:8069
