name: Deploy Odoo with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-venv python3-pip libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev build-essential libssl-dev libmysqlclient-dev postgresql wkhtmltopdf

      - name: Start PostgreSQL service
        run: |
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo systemctl status postgresql

      - name: Install PostgreSQL and configure user
        run: |
          sudo -u postgres psql -c "CREATE USER odoo WITH PASSWORD 'odoo';"
          sudo -u postgres psql -c "CREATE DATABASE odoo OWNER odoo;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE odoo TO odoo;"

      - name: Create Odoo virtual environment
        run: |
          cd /opt
          git clone --branch 16.0 https://github.com/odoo/odoo.git ./odoo
          sudo chown $USER:$USER odoo
          cd odoo
          python3 -m venv odoo-venv
          source odoo-venv/bin/activate
          pip install -r /opt/odoo/requirements.txt

      - name: Crear archivo de configuración de Odoo
        run: |
          sudo bash -c 'cat > /etc/odoo.conf <<EOF
          [options]
             admin_passwd = admin
             db_host = localhost
             db_port = 5432
             db_user = odoo
             db_password = odoo
             db_name = odoo
             addons_path = /opt/odoo/addons
             logfile = /var/log/odoo/odoo.log
          EOF'

      - name: Create necessary directories for Odoo logs
        run: |
          sudo mkdir /var/log/odoo
          sudo chown $USER:$USER /var/log/odoo

      - name: Start Odoo
        run: |
          cd /opt/odoo
          source odoo-venv/bin/activate
          ./odoo-bin -c /etc/odoo.conf &

      - name: Wait for Odoo to start
        run: |
          until curl -s http://localhost:8069; do
            echo "Waiting for Odoo to start..."
            sleep 5
          done

      - name: Display Odoo URL
        run: |
          echo "Odoo is running at http://localhost:8069"

      - name: Test Odoo Deployment
        run: |
          curl http://localhost:8069
