name: Deploy Odoo with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U odoo" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev build-essential libssl-dev libmysqlclient-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Wkhtmltopdf for reports
        run: |
          sudo apt-get install -y wkhtmltopdf

      - name: Update pg_hba.conf for md5 authentication
        run: |
          sudo sed -i "s/local   all             all                                     peer/local   all             all                                     md5/" /etc/postgresql/*/main/pg_hba.conf
          sudo systemctl restart postgresql

      - name: Set password for odoo user in PostgreSQL
        run: |
          sudo -u postgres psql -c "ALTER USER odoo WITH PASSWORD 'odoo';"

      - name: Start Odoo
        run: |
          cd /opt/odoo
          source odoo-venv/bin/activate
          ./odoo-bin -c /etc/odoo.conf &

      - name: Wait for Odoo to start
        run: |
          until curl -s http://localhost:8069; do
            echo "Waiting for Odoo to start..."
            sleep 5
          done     

      - name: Test deployment
        run: |
          curl http://localhost:8069
