name: Deploy Odoo with PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U odoo" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev libsasl2-dev libldap2-dev build-essential libssl-dev libmysqlclient-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Odoo Repository
        uses: actions/cache@v3
        with:
          path: ~/odoo
          key: odoo-${{ github.sha }}
          restore-keys: |
            odoo-

      - name: Clone Odoo from GitHub (if not cached)
        run: |
          if [ ! -d "~/odoo" ]; then
            git clone --depth=1 --branch 16.0 https://github.com/odoo/odoo.git ~/odoo
          else
            echo "Odoo repository restored from cache."
          fi

      - name: Install Odoo dependencies
        run: |
          cd ~/odoo
          pip install -r requirements.txt

      - name: Start Odoo
        run: |
          nohup python3 ~/odoo/odoo-bin --config=./odoo.conf -d odoo -i base &

      - name: Wait for Odoo to start
        run: |
          until curl -s http://localhost:8069; do
            echo "Waiting for Odoo to start..."
            sleep 5
          done     

      - name: Test deployment
        run: |
          curl http://localhost:8069
