name: Deploy Odoo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U odoo"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Odoo image
        run: |
          docker build -t odoo-local .

      - name: Run Odoo
        run: |
          docker network create odoo-net || true
          docker run -d --name odoo \
            --network=odoo-net \
            -p 8069:8069 \
            --env HOST=postgres \
            --env POSTGRES_DB=odoo \
            --env POSTGRES_USER=odoo \
            --env POSTGRES_PASSWORD=odoo \
            odoo-local
          
      - name: Wait for Odoo to be ready
        run: sleep 30

      - name: Test Odoo
        run: curl -I http://localhost:8069
